# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Probably Approximately Wrong
description: Quantifyin' how much I don't know
github_username: nicola144

# Disqus Comments
# disqus:
#     # Leave shortname blank to disable comments site-wide.
#     # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
#     shortname: disqus_bYJiqg30hK

# Email and twitter are optional:
email:
twitter_username: Branchini97
google-scholar: nbranchini17@gmail.com

# Set this to true to get LaTeX math equation support
use_math: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics: UA—178399856-1

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
mathjax: true
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
